FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Museumary

Museumary is a simple API used to retrieve data on art by
specific artwork, artist, location, and type of art.

## group Artwork Collection

## All Works [/work{?page,entries_per_page}/]
### List All Artworks [GET]

+ Parameters
    + page (optional, integer) ...index of the page being requested; default=1
    + entries_per_page (optional, integer) ...number of entries to be returned; default=25

+ Response 200 (application/json)

    + Body
    
            {
                "info": {
                    "page": 1,
                    "entries_per_page": 3,
                    "num_entries": 900,
                    "num_pages": 300
                },
                
                "objects": [
                    {
                        "id": 0,
                        "name": "The Wounded Veteran",
                        "artist_id": 35,
                        "art_type_id": 10,
                        "medium_id": 4,
                        "date": "c. 1882-1883",
                        "venue_id": 1,
                        "image_url": None
                    },
                    {
                        "id": 1,
                        "name": "Envy",
                        "artist_id": 45,
                        "art_type_id": 11,
                        "medium_id": 9,
                        "date": "1966-1967",
                        "venue_id": 1,
                        "image_url": None
                    },
                    {
                        "id": 2,
                        "name": "The Pomegranate",
                        "artist_id": 53,
                        "art_type_id": 12,
                        "medium_id": 8,
                        "date": "1911-1912",
                        "venue_id": 1,
                        "image_url": None
                    }
                ]
            }

## Single Work [/work/{work_id}]
### Specific Artwork [GET]

+ Parameters
    + work_id (required, integer) ...ID of the requested artwork

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Envy",
                "artist_id": 45,
                "art_type_id": 11,
                "medium_id": 9,
                "date": "1966-1967",
                "venue_id": 1,
                "image_url": None
            }
          
## group Artist Collection

## All Artists [/artist{?page,entries_per_page}/]
### List All Artists [GET]

+ Parameters
    + page (optional, integer) ...index of the page being requested; default=1
    + entries_per_page (optional, integer) ...number of entries to be returned; default=25

+ Response 200 (application/json)

    + Body
    
            {   
                "info": {
                    "page": 1,
                    "entries_per_page": 3,
                    "num_entries": 900,
                    "num_pages": 300
                },
                
                "artists": [
                    {
                        "id": 0,
                        "name": "Vincent van Gogh",
                        "birth": "1853",
                        "death": "1890",
                        "birthplace": "Groot Zundert (Zundert), The Netherlands",
                        "deathplace": "Auvers-sur-Oise, France",
                        "culture": "Dutch",
                        "image_url": None,
                        "art_type_ids": [23, 26, 27],
                        "work_ids": [32, 67, 43]
                    },
                    {
                        "id": 1,
                        "name": "Salvador Dali",
                        "birth": "1904",
                        "death": "1989",
                        "birthplace": "Figueres, Spain",
                        "deathplace": "Figueres, Spain",
                        "culture": "Spanish",
                        "image_url": None,
                        "art_type_ids": [28, 29],
                        "work_ids": [24, 90]
                    },
                    {
                        "id": 2,
                        "name": "Pablo Ruiz Picasso",
                        "birth": "1881",
                        "death": "1973",
                        "birthplace": "Malaga, Spain",
                        "deathplace": "Mougins, France",
                        "culture": "Spanish",
                        "image_url": None,
                        "art_type_ids": [31, 35],
                        "work_ids": [81]
                    }
                ]
            }

## Single Artist [/artist/{artist_id}]
### Specific Artist [GET]

+ Parameters
    + artist_id (required, integer) ...ID of the requested artist

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Salvador Dali",
                "birth": "1904",
                "death": "1989",
                "birthplace": "Figueres, Spain",
                "deathplace": "Figueres, Spain",
                "culture": "Spanish",
                "image_url": None,
                "art_type_ids": [28, 29],
                "work_ids": [24, 90]
            }

## group Venues

## All Venues [/venue{?page,entries_per_page}/]
### List All Venues [GET]

+ Parameters
    + page (optional, integer) ...index of the page being requested; default=1
    + entries_per_page (optional, integer) ...number of entries to be returned; default=25

+ Response 200 (application/json)

    + Body
    
            {
                "info": {
                    "page": 1,
                    "entries_per_page": 25,
                    "num_entries": 5,
                    "num_pages": 1
                },
                
                "venues": [
                    {
                        "id": 0,
                        "name": "Harvard Art Museum",
                        "country" : "USA",
                        "city": "Cambridge, MA",
                        "work_ids": [18, 20, 35],
                        "street": "32 Quincy St",
                        "zipcode": "02138"
                    },
                    {
                        "id": 1,
                        "name": "The Walters Art Museum",
                        "country" : "USA",
                        "city": "Baltimore, MD",
                        "work_ids": [3],
                        "street": "600 N. Charles Street",
                        "zipcode": "21201"
                    },
                    {
                        "id": 2,
                        "name": "Auckland Museum",
                        "country" : "New Zealand",
                        "city": "Auckland",
                        "work_ids": [14, 25],
                        "street": "The Auckland Domain, Parnell",
                        "zipcode": "Auckland 1010"
                    },
                    {
                        "id": 3,
                        "name": "Cooper Hewitt, Smithsonian Design Museum",
                        "country" : "USA",
                        "city": "New York, NY",
                        "work_ids": [2, 5],
                        "street": "2 E 91st St",
                        "zipcode": "10128"
                    },
                    {
                        "id": 4,
                        "name": "Finish National Gallery",
                        "country" : "Finland",
                        "city": "Helsinki",
                        "work_ids": [1],
                        "street": "Kaivokatu 2",
                        "zipcode": "00100 Helsinki"
                    }
                ]
            }
        
## Single Venue [/venue/{venue_id}]
### Specific Venue [GET]

+ Parameters
    + venue_id (required, integer) ...ID of the requested venue

+ Response 200 (application/json)

    + Body

            {
                "id": 0,
                "name": "Harvard Art Museum",
                "country" : "USA",
                "city": "Cambridge, MA",
                "work_ids": [18, 20, 35],
                "street": "32 Quincy St",
                "zipcode": "02138"
            }

## group Art Type

## All Art Types [/art_type{?page,entries_per_page}/]
### List All Types [GET]

+ Parameters
    + page (optional, integer) ...index of the page being requested; default=1
    + entries_per_page (optional, integer) ...number of entries to be returned; default=25

+ Response 200 (application/json)

    + Body
    
            {
                "info": {
                    "page": 1,
                    "entries_per_page": 5,
                    "num_entries": 900,
                    "num_pages": 180
                },
                
                "types": [
                    {
                        "id": 0,
                        "name": "painting",
                        "medium_ids": [2, 3],
                        "artist_ids": [24],
                        "work_ids": [65]
                    },
                    {
                        "id": 1,
                        "name": "drawing",
                        "medium_ids": [4, 5, 6],
                        "artist_ids": [15],
                        "work_ids": [14]
                    },
                    {
                        "id": 2,
                        "name": "print",
                        "medium_ids": [7, 9],
                        "artist_ids": [19],
                        "work_ids": [40, 58, 32]
                    },
                    {
                        "id": 3,
                        "name": "ceramics",
                        "medium_ids": [10],
                        "artist_ids": [15, 19],
                        "work_ids": [23]
                    },
                    {
                        "id": 4,
                        "name": "photograph",
                        "medium_ids": [11, 16],
                        "artist_ids": [26, 38, 67],
                        "work_ids": [13, 15, 29]
                    }
                ]
            }

## Single Art Type [/art_type/{art_type_id}]
### Specific Type [GET]

+ Parameters
    + art_type_id (required, integer) ...ID of the requested art form

+ Response 200 (application/json)

    + Body

            {
                "id": 4,
                "name": "photograph",
                "medium_ids": [11, 16],
                "artist_ids": [26, 38, 67],
                "work_ids": [13, 15, 29]
            }