FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# museumary

Museumary is a simple API used to retrieve data on art by
specific artwork, artist, location, and type of art.

## Artwork Collection [/artworks]

### List All Artworks [GET]

+ Response 200 (application/json)

        [
            {
                "id": "0",
                "name": "The Wounded Veteran",
                "artist": "Vincent can Gogh",
                "type": "drawing",
                "data": "c. 1882-1883",
                "culture": "Dutch",
                "location": "Harvard Art Museum"
            },
            {
                "id": "1",
                "name": "Envy",
                "artist": "Salvador Dali",
                "type": "print",
                "data": "1966-1967",
                "culture": "Spanish",
                "location": "Harvard Art Museum"
            },
            {
                "id": "2",
                "name": "The Pomegranate",
                "artist": "Pablo Ruiz Picasso",
                "type": "painting",
                "data": "1911-1912",
                "culture": "Spanish",
                "location": "Harvard Art Museum"
            }
        ]

### Specific Artwork [GET]

+ Parameters
    + id (required, integer) ...ID of the requested artwork

+ Response 200 (application/json)

    + Headers

            Location: /artworks/id

    + Body

        {
            "id": "1",
            "name": "Envy"
            "artist": "Salvador Dali"
            "type": "print"
            "data": "1966-1967"
            "culture": "Spanish"
        }
            
## Artists [/artists]

### List All Artists [GET]

+ Response 200 (application/json)

        [
            {
                "id": "0",
                "name": "Vincent van Gogh",
                "birth": "1853",
                "death": "1890",
                "birthplace": "Groot Zundert (Zundert), The Netherlands",
                "deathplace": "Auvers-sur-Oise, France",
                "artwork_ids": ["0"],
                "culture": "Dutch"
            },
            {
                "id": "1",
                "name": "Salvador Dali",
                "birth": "1904",
                "death": "1989",
                "birthplace": "Figueres, Spain",
                "deathplace": "Figueres, Spain",
                "artwork_ids": ["1"],
                "culture": "Spanish"
            },
            {
                "id": "2",
                "name": "Pablo Ruiz Picasso",
                "birth": "1881",
                "death": "1973",
                "birthplace": "Malaga, Spain",
                "deathplace": "Mougins, France",
                "artwork_ids": ["2"],
                "culture": "Spanish"
            }
        ]

### Specific Artist [GET]

+ Parameters
    + id (required, integer) ...ID of the requested artist

+ Response 200 (application/json)

    + Headers

            Location: /artists/id

    + Body

        {
            "id": "1",
            "name": "Salvador Dali",
            "birth": "1904",
            "death": "1989",
            "birthplace": "Figueres, Spain",
            "deathplace": "Figueres, Spain",
            "artwork_ids": ["1"],
            "culture": "Spanish"
        }

## Museums [/museums]

### List All Museums [GET]
### Specific Museum [GET]

## Types of Art [/types]

### List All Types [GET]
### Specific Type [GET]